Adding a Vagrantfile
redhat-beyond/Beyond-07-team-4 pull request #1
Opened 2022-03-02 17:19 UTC by ShirleyFichman

**Adding a Vagrantfile for spinning up a development VM.**

Vagrant is a tool for using virtual machines to share development environments.
Learn more about it at:
https://www.vagrantup.com/

Please make sure you have Vagrant installed on your computer, if not then you can download from here:
https://www.vagrantup.com/downloads

Also, make sure that you have VirtualBox installed. VirtualBox is a hypervisor, which lets us create and run virtual machines.
The page below include links for downloading VirtualBox for various OS:
https://www.virtualbox.org/wiki/Downloads

In order for it all to work, please enable virtualization hardware on your computer. An explanation on how to do it can be found here:
https://www.virtualmetric.com/blog/how-to-enable-hardware-virtualization

Then, when you have all those you can bring up the VM by using the command: vagrant up.

Now that the Vagrant is up, we can verify everything is working by accessing it with the command: vagrant ssh
Now the prompt should show: [vagrant@localhost]$

**Also making changes to the `.gitignore` file to ignore any data that Vagrant might create.**

**Close #2**

2022-03-02 17:24 UTC, rotemHay commented
Looks good to me

2022-03-02 17:25 UTC, paOmer commented
Looks good to me

2022-03-02 17:45 UTC, taljacob2 requested changes
Hi, please enable the line I mentioned.
It enables us to view the application on `127.0.0.1:8000`.

2022-03-02 17:45 UTC, taljacob2 commented on Vagrantfile
> +  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
Hi, please enable this line and match it with the following:
```
config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"
```

2022-03-02 17:50 UTC, paOmer approved these changes
Looks good to me

2022-03-03 07:18 UTC, Yarboa commented
Question here
It is written in the doc,
> A working Vagrant environment that brings up the default Django web server

I would consider updating the readme with the follwoing:
 prerequisites,
 hot to run vagrant, and verify it is up

2022-03-03 07:43 UTC, taljacob2 commented
> Question here It is written in the doc,
> 
> > A working Vagrant environment that brings up the default Django web server
> 
> I would consider updating the readme with the follwoing: prerequisites, how to run vagrant, and verify it is up

No problem, I would do it when I'll edit the `README.md` and `CONTRIBUTING.md` all together.
I will create an issue with your notes above, and assign myself.

2022-03-03 08:25 UTC, Yarboa commented
> > Question here It is written in the doc,
> > > A working Vagrant environment that brings up the default Django web server
> > 
> > 
> > I would consider updating the readme with the follwoing: prerequisites, how to run vagrant, and verify it is up
> 
> @Yarboa No problem, I would do it when I'll edit the `README.md` and `CONTRIBUTING.md` all together. I will create an issue with your notes above, and assign myself.

I would suggest, to update whatever needed to run this PR,
Make nicer README should be other issue, 

Whatever we upload should be clear, and run able
This PR is dealing with vagrant, if i am clueless person, i do no know how to continue

2022-03-03 13:03 UTC, Yarboa commented
> > > Question here It is written in the doc,
> > > > A working Vagrant environment that brings up the default Django web server
> > > 
> > > 
> > > I would consider updating the readme with the follwoing: prerequisites, how to run vagrant, and verify it is up
> > 
> > 
> > @Yarboa No problem, I would do it when I'll edit the `README.md` and `CONTRIBUTING.md` all together. I will create an issue with your notes above, and assign myself.
> 
> I would suggest, to update whatever needed to run this PR, Make nicer README should be other issue,
> 
> Whatever we upload should be clear, and run able This PR is dealing with vagrant, if i am clueless person, i do no know how to continue

Good work,
Please move all the content of the initial comment into this file
https://github.com/redhat-beyond/Beyond-07-team-4/blob/main/README.md

later on others will rebase and extend the README,
Lets merge it after the next commit

2022-03-06 08:30 UTC, Yarboa commented
LGTM, I would advise for next time, to include in PR what ever needed

2022-03-06 08:30 UTC, merged