Added Flake8 CI Github-Action For Python
redhat-beyond/Beyond-07-team-4 pull request #10
Opened 2022-03-04 11:28 UTC by taljacob2

*Flake8* is a CI tool that checks the code written in python.
> For example, it checks that the max-line-length is below 120
characters.

- **Added Support For *Flake8* In The Project**
    - Added *Flake8* as a dependency for *Pipenv* sync.
	- **How To Use *Flake8*:**
	  After running the commands:
	  ```
	  vagrant up
	  vagrant ssh
	  cd /vagrant
	  ```
	  you may run *Flake8* and review your code,
	  by running the command:
	  ```
	  pipenv run flake8 --max-line-length 120
	  ```
- **Added Support For Github's PRs To CI With *Flake8***
	When contributing a PR, Github will now review the code in it
	with *Flake8*, and will print the results of it.

DEPENDS ON #5

**ATTENTION:**
Because of insufficient writing-permissions to this
repository, it is required that @Yarboa, @kasemAlem
will [setup *branch-protection*][1] of the `main` branch,
so this PR would
close #8

[1]: https://github.com/redhat-beyond/Beyond-07-team-4/issues/8#:~:text=In%20Github%2C%20setup,create%20the%20rule.

Signed-off-by: taljacob2 <taljacob2@gmail.com>

2022-03-04 11:49 UTC, ShirleyFichman approved these changes
LGTM

2022-03-06 09:46 UTC, kasemAlem reviewed
Is File README file updated accordingly with these changes?

2022-03-06 10:43 UTC, kasemAlem requested changes
Must be documented in README

2022-03-06 11:42 UTC, taljacob2 commented
> Must be documented in README

Alright. I will create a special README file that explains all the information about the *Flake8* tool and how to use it. I will place it in a new README folder.

2022-03-06 14:02 UTC, Yarboa requested changes
This PR deals only with workflow
I think it should contain only 3 files, isnt it?

2022-03-06 20:24 UTC, taljacob2 commented
**Updates of today:**
- @kasemAlem : There is a new [README](README/Flake8.md) file for *Flake8*, that explains how to use it.
- @Yarboa : This PR now contains only the files added in this new feature.

Please review the new changes.

2022-03-07 07:56 UTC, Yarboa reviewed
Consider renaming README dir to docs

2022-03-07 07:57 UTC, Yarboa approved these changes

2022-03-07 08:30 UTC, taljacob2 commented
> Consider renaming README dir to docs

Done.
The *Flake8*'s README is now placed at: `docs/Flake8.md`

2022-03-07 09:56 UTC, merged